### ISSUE TITLE
Adding Quick Actions

### ISSUE THREAD

**Issue by dsymhoven** [dsymhoven/timerApp#11]

**Comment by alexkaessner** [comment]
I would say I will add some icons for these actions? Wich one do you want to add?

**Comment by dsymhoven** [comment]
Let's try Start Timer with 60, 90 and 120 seconds

**Comment by alexkaessner** [comment]
We could use the "Time" icon from the [system icons](https://developer.apple.com/ios/human-interface-guidelines/graphics/system-icons/#quick-action-icons). Or maybe better this icon with number labels, but this would be twice the time…
